### ISSUE TITLE
Issues with auto append

### ISSUE THREAD

**Issue by ale-rt** [collective/collective.z3cform.datagridfield#104]
It seems that once again the auto append mode cannot be disabled.
It was already reported in #66 and  fixed in #65 (relevant commit 12a70b28e47848582fb99464bccd2f5bd6b2772f).
That change was lost after https://github.com/collective/collective.z3cform.datagridfield/commit/cce15c4462117408b2773e9995f16e1d24cd2090?w=1#diff-590e98fb6789414d6cc1e43f66e1a1a459d13b94b69554dd1711c15c976bbce3L95-L97, part of PR #79.

Looking at the history of the issue in the repo (#82, #92, #96) there might be more to fix

**Comment by thet** [comment]
Should be fixed with: https://github.com/collective/collective.z3cform.datagridfield/pull/106
