### ISSUE TITLE
Imports removal (__init__.py) leads to ImportError & obsolete documentation

### ISSUE THREAD

**Issue by laulaz** [collective/collective.z3cform.datagridfield#110]
The problem comes from this commit : 6e11a31fdea4012fab5a921740bcaa6ce51c3638

README file and many products rely on :
`from collective.z3cform.datagridfield import DataGridFieldFactory`
but this import does not work anymore.

Should we either:
- restore removed imports
- update documentation & add deprecated imports

@thet @jensens ?

**Comment by laulaz** [comment]
We still have an issue here right ?
https://github.com/collective/collective.z3cform.datagridfield/blob/5685c41d6af55c07aa72a038f8c8cf5b29550460/src/collective/z3cform/datagridfield/registry.py#L2

**Comment by jensens** [comment]
Reintroducing circular imports is probably a bad idea. Better fix the calling code.
