### ISSUE TITLE
Shouldn't the datagridfield_input template respect view/klass or at least view/display_table_css_class ?

### ISSUE THREAD

**Issue by mtrebron** [collective/collective.z3cform.datagridfield#119]
While working on a standalone Plone form, `MyForm(AutoExtensibleForm, form.Form)` where one of the fields is a DataGrid, I thought it useful to add the css _listing_ class to my widget to take advantage of even and odd colored rows in the Barceloneta theme.

Adding a klass attribute to either the widget directives or in my custom WidgetFactory did not work, nor did the widget.addClass() method.  

I investigated further and found that the [datagrid_input](https://github.com/collective/collective.z3cform.datagridfield/blob/master/src/collective/z3cform/datagridfield/datagridfield_input.pt#L10) template completely ignores the setting, and the [datagrid_display](https://github.com/collective/collective.z3cform.datagridfield/blob/c47d3a5019a3a62566925dda445495cc9de96256/src/collective/z3cform/datagridfield/datagridfield_display.pt#L11) template only considers `view/display_table_css_class`

What is the purpose of setting klass to "datagridfield" [here](https://github.com/collective/collective.z3cform.datagridfield/blob/master/src/collective/z3cform/datagridfield/datagridfield.py#L66)? Is there a particular reason for ignoring these settings in the templates?

**Comment by mtrebron** [comment]
I just noticed: https://github.com/collective/collective.z3cform.datagridfield/issues/15 @gbastien since you were involved in the original implementation, do you have an opinion?

**Comment by petschki** [comment]
this got implemented here https://github.com/collective/collective.z3cform.datagridfield/pull/131
