### ISSUE TITLE
Cleaning up extra .cfg files

### ISSUE THREAD

**Issue by miohtama** [collective/collective.z3cform.datagridfield#13]
Hi @jaroel ,

Could it be possible remove extra .cfg files from collective.z3cform.datagridfild root?

Also for files, which are still needed, add a comment at the beginning of the file why it is needed and what it is used for.

I am not sure anymore which are relevant and which not :(

**Comment by jensens** [comment]
I cleaned it up - and much more.

**Comment by jaroel** [comment]
Thanks!
