### ISSUE TITLE
Bug introduced with new DictRowConverter -> BooleanWidget gets set to `True` when editing.

### ISSUE THREAD

**Issue by petschki** [collective/collective.z3cform.datagridfield#155]
If you have a `schema.Bool` in your DictRow schema it always gets set to True when you enter the edit mode... event if you do not save the content, its saved to the schema. I'm currently working on that here #154 ... can anybody else confirm this?

/cc @laulaz

**Comment by petschki** [comment]
Got it ... the converter changed the original data itself which lead to side effects.

**Comment by Arkusm** [comment]
Another mistake could be related to this. Relation fields can no longer be saved if plone.versioning is activated (Can't pickle objects in acquisition wrappers). In addition, (non-functioning) objects are now saved in relation fields. There should be z3c.relationfield.relation.RelationValue

**Comment by petschki** [comment]
> Another mistake could be related to this. Relation fields can no longer be saved if plone.versioning is activated (Can't pickle objects in acquisition wrappers). In addition, (non-functioning) objects are now saved in relation fields. There should be z3c.relationfield.relation.RelationValue

I don't think this has to do something with datagridfield? If I'm wrong, please open a new issue with a traceback 🙏🏼
