### ISSUE TITLE
Is it possible to upload images using NamedBlobImage in a data grid?

### ISSUE THREAD

**Issue by neilferreira** [collective/collective.z3cform.datagridfield#25]
Is it possible to upload images into a data grid?

I'm getting this backtrace when I try

Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in **call**
  Module plone.z3cform.layout, line 60, in update
  Module z3c.form.form, line 158, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 2ba401494e66754dd01a4fa28c80e723.py, line 91, in render
  Module dcee88d0c7d8c247e5bc3e6ec19f29a2.py, line 1808, in render_titlelessform
  Module dcee88d0c7d8c247e5bc3e6ec19f29a2.py, line 451, in render_fields
  Module dcee88d0c7d8c247e5bc3e6ec19f29a2.py, line 126, in render_widget_rendering
  Module dcee88d0c7d8c247e5bc3e6ec19f29a2.py, line 1077, in render_field
  Module five.pt.expressions, line 161, in **call**
  Module Products.Five.browser.metaconfigure, line 479, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 83, in **call**
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 237f5faa9981a2568a3a7717871fd934.py, line 590, in render
  Module 237f5faa9981a2568a3a7717871fd934.py, line 465, in render_widget_wrapper
  Module five.pt.expressions, line 161, in **call**
  Module z3c.form.widget, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 7ba056c4d0306e53b2d20fb81f62142a.py, line 981, in render
  Module 7ba056c4d0306e53b2d20fb81f62142a.py, line 820, in render_widget_row
  Module five.pt.expressions, line 161, in **call**
  Module z3c.form.object, line 310, in render
  Module z3c.form.widget, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 170, in render
  Module 642e3a9d917c5effeed974bd252be034.py, line 457, in render
  Module five.pt.expressions, line 161, in **call**
  Module z3c.form.widget, line 153, in render
  Module zope.browserpage.viewpagetemplatefile, line 51, in **call**
  Module zope.pagetemplate.pagetemplate, line 132, in pt_render
  Module five.pt.engine, line 93, in **call**
  Module z3c.pt.pagetemplate, line 149, in render
  Module chameleon.zpt.template, line 258, in render
  Module chameleon.template, line 188, in render
  Module chameleon.template, line 170, in render
  Module dbbbcbb6b82fef5f3fbfc72a1cb7fd26.py, line 163, in render
  Module five.pt.expressions, line 154, in **call**
  Module five.pt.expressions, line 126, in traverse
  Module zope.traversing.adapters, line 136, in traversePathElement
- **traceback_info**: (<NamedImageWidget 'form.widgets.images.0.widgets.image'>, 'file_icon')
  Module zope.traversing.adapters, line 50, in traverse
- **traceback_info**: (<NamedImageWidget 'form.widgets.images.0.widgets.image'>, 'file_icon', ())
  LocationError: (<NamedImageWidget 'form.widgets.images.0.widgets.image'>, 'file_icon')
  - Expression: "widget/@@ploneform-render-widget"
  - Filename:   ... rm-0.7.6-py2.7.egg/plone/app/z3cform/templates/macros.pt
  - Location:   (line 97: col 81)
  - Source:     ... place="structure widget/@@ploneform-render-widget"/>
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  - Expression: "view/file_icon"
  - Filename:   ... .0.9-py2.7.egg/plone/formwidget/namedfile/image_input.pt
  - Location:   (line 30: col 15)
  - Source:     icon view/file_icon;">
             ^
  - Arguments:  repeat: {...} (0)
             context: {...} (2)
             exists: True
             views: <ViewMapper - at 0x9cb6410>
             modules: <TraversableModuleImporter - at 0x3ca6790>
             args: <tuple - at 0x7f08a393b050>
             nothing: <NoneType - at 0x8593c0>
             target_language: <NoneType - at 0x8593c0>
             doc_type: JPEG image
             allow_nochange: True
             default: <object - at 0x7f08a38a74f0>
             request: <instance - at 0x7f08954f30e0>
             wrapped_repeat: {...} (0)
             download_url: http://127.0.0.1:8080/Site/foo/@@edit/++widget++f...
             filename: foo.jpg
             loop: {...} (0)
             template: <ViewPageTemplateFile - at 0x8a96450>
             action: nochange
             translate: <function translate at 0x7f088c458ed8>
             options: {...} (0)
             view: <NamedImageWidget image at 0x91a1710>

**Comment by jensens** [comment]
close here, go on with #2
