### ISSUE TITLE
BlockDataGridFieldFactory can not be imported

### ISSUE THREAD

**Issue by birdwell** [collective/collective.z3cform.datagridfield#32]
Using: from collective.z3cform.datagridfield import BlockDataGridFieldFactory
Results in an import error however, I can use the DataGridFieldFactory just fine.

**Comment by espenmn** [comment]
This is a version problem, datagridfield is pinned to 0.11  (which must be wrong ) in 
http://dist.plone.org/release/4.3-latest/versions.cfg
