### ISSUE TITLE
Version for Plone 4.3  ++

### ISSUE THREAD

**Issue by espenmn** [collective/collective.z3cform.datagridfield#33]
I noticed that 
http://dist.plone.org/release/4.3-latest/versions.cfg

pins collective.z3cform.datagridfield to version 0.11
Any reason why it is pinned to such an old version ?

**Comment by hvelarde** [comment]
probably because nobody has taken the time to update it :-)

I once used v0.15 on a project with Plone 4.3 and it still had some issues.

**Comment by jensens** [comment]
This one is old. 
It is invalid here and should be moved to ``buildout.coredev`` issue tracker - if this is still an issue please do so.
