### ISSUE TITLE
remove grok from all documentation since grok is no longer supported

### ISSUE THREAD

**Issue by jensens** [collective/collective.z3cform.datagridfield#36]
Grok is not best practice and should be removed from docs and (if there, need check) code.

**Comment by jensens** [comment]
Note: this means to not use ``plone.directives`` as well (superfluos, all directives were moved to core packages meanwhile).

**Comment by hvelarde** [comment]
@jensens you mean in Plone 5?

**Comment by jensens** [comment]
plone.autoformand + plone.supermodel is both on master (4.3/5.0) and are providing the methods.
https://github.com/plone/plone.autoform/blob/master/plone/autoform/directives.py
https://github.com/plone/plone.supermodel/blob/master/plone/supermodel/directives.py

plone.directives.form only bbb imports form there.
https://github.com/plone/plone.supermodel/blob/master/plone/supermodel/directives.py

**Comment by hvelarde** [comment]
crap, we need to update the documentation also...
