### ISSUE TITLE
Broken with z3c.form > 3.3

### ISSUE THREAD

**Issue by Martronic-SA** [collective/collective.z3cform.datagridfield#45]
ObjectSubForm and SubformAdapter have been removed in z3c.form so datagridfield is no more working on latest versions of z3c.form.

I don't know if it will be possible and how to fix

**Comment by jensens** [comment]
We need to move on supporting newer z3c.form versions in Plone. This package is the major reason (even if not in core) why plone/buildout.coredev#278 together with plone/plone.app.z3cform#52 were not merged already.

Since I'm not very deep into this package, any ideas how to get around this?

**Comment by jensens** [comment]
I am working on this. 5.1 coredev is now using the newest z3c.form.
Expect results soon, since I need it.

**Comment by jensens** [comment]
master works now with z3c.form 3.4.0 on Plone 5.1

it looks like Plone 4.3 works as well (test are green)

there is a hiccup in 5.0 tests, so, instance fires up locally and demo works fine
