### ISSUE TITLE
plone 5 release

### ISSUE THREAD

**Issue by djay** [collective/collective.z3cform.datagridfield#47]
The code has been updated to be compatible for plone 5. can a release be done?

**Comment by hvelarde** [comment]
seems to me CI integration is failing and package documentation has not being updated; I think it might be important to take care of those things before making a release:

https://travis-ci.org/collective/collective.z3cform.datagridfield

**Comment by djay** [comment]
done

**Comment by jensens** [comment]
ping @vangheem @davisagli @tdesvenain (just a few of those who have pypi access) may you do a release or either grant @djay @hvelarde or me access to do so?

**Comment by vangheem** [comment]
added you all as maintainers. collective also has access.

**Comment by jensens** [comment]
@vangheem thanks. but who is collective?

**Comment by jensens** [comment]
released as 1.2
