### ISSUE TITLE
Cannot open addform anymore

### ISSUE THREAD

**Issue by jone** [collective/collective.z3cform.datagridfield#58]
Since the newest commit 87ef06aa0dbd9860cd054cce2d95b2d3d10a5318 I cannot open the addform anymore (it did work with 82a3eaa71b2c2668290e39a3979ae521042b2a13).
@jensens any idea what went wrong?
What is the intention of the commit 87ef06aa0dbd9860cd054cce2d95b2d3d10a5318 ?

I'm using Plone `4.3.11` and I'm getting this traceback:
```python
b2017-03-22 09:34:53 ERROR Zope.SiteErrorLog 1490171693.840.254497882331 http://localhost:8080/Plone/++add++ftw.book.Table
Traceback (innermost last):
  Module ZPublisher.Publish, line 138, in publish
  Module ZPublisher.mapply, line 77, in mapply
  Module ZPublisher.Publish, line 48, in call_object
  Module plone.z3cform.layout, line 66, in __call__
  Module plone.z3cform.layout, line 50, in update
  Module plone.dexterity.browser.add, line 118, in update
  Module plone.z3cform.fieldsets.extensible, line 59, in update
  Module plone.z3cform.patch, line 30, in GroupForm_update
  Module z3c.form.group, line 141, in update
  Module z3c.form.group, line 52, in update
  Module z3c.form.group, line 48, in updateWidgets
  Module z3c.form.field, line 277, in update
  Module z3c.form.browser.multi, line 63, in update
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.widget, line 496, in update
  Module z3c.form.widget, line 132, in update
  Module z3c.form.widget, line 491, in value
  Module collective.z3cform.datagridfield.datagridfield, line 170, in updateWidgets
  Module z3c.form.widget, line 432, in updateWidgets
  Module collective.z3cform.datagridfield.datagridfield, line 148, in getWidget
  Module z3c.form.browser.widget, line 171, in update
  Module z3c.form.object, line 217, in update
  Module collective.z3cform.datagridfield.datagridfield, line 310, in updateWidgets
  Module z3c.form.util, line 259, in __getitem__
KeyError: 'columnId'
```

**Comment by jone** [comment]
@jensens can you give me an update here?
I think you broke Plone 4 support in `master` (87ef06a), and I would really like to have a Plone-4 compatible release with my change (#56).
So: are you still working on this? What is your plan?

**Comment by jensens** [comment]
I am still working on this but was not aware we support 4.3 on master. This week I am at PLOG in Sorrento, the week after I have time to look into this.

**Comment by jone** [comment]
@jensens Cool, thanks. I wasn't aware that master is Plone 5 😜 
How about making a Plone 4 branch from a state before your Plone 5 changes and making a Plone 4 release from there?
Unfortunately I have no pypi permissions for this package..

**Comment by jensens** [comment]
@jone +1 
I do not have permissions to give you a role there (I am just "Maintainer").
 But if you want to prepare it I can cut a release.

**Comment by jone** [comment]
@jensens sure.
Should we make the master `2.x` (Plone 5) and therefore have an `1.x` for Plone 4?
Or `1.3` / `1.2.x`?

There is already a `1.2.x` branch for Plone 4, which could be released as it is.

**Comment by jensens** [comment]
update:

- runs on 5.1 (including tests) and also a real live project against coredev works with it.
- on 5.0 it has test failures, but the demo works. I did not try with Dexterity types.
- on 4.3 test are running on travis, no local testing so far.

Regarding a 2.0 for 5.x only: +1 from my side. I don't care much about 4.3. 

I have at the moment no clue why the test fails on 5.0. This needs investigations.

**Comment by jensens** [comment]
@jone I increased the version to 2.0. It works all very fine with z3c.form 3.4 and plone.app.z3cform 3.0.
On 5.1 all is green and works as expected, including patternslib usage in subforms.

5.0 and 4.3 states are still as in my comment above.

**Comment by jensens** [comment]
ah, I broke it again, stay tuned ....

**Comment by jensens** [comment]
No, it does not work with z3c.form 3.4 and plone.app.z3cform 3.0 in Plone 5.1.
