### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by hvelarde** [collective/collective.z3cform.datagridfield#63]
Dependency on five.grok is already removed on the master branch; is there any reason we haven't released 1.3 yet?

**Comment by tkimnguyen** [comment]
I've asked Nathan to give me Owner role for this on pypi.

**Comment by hvelarde** [comment]
seems I can do it.

**Comment by hvelarde** [comment]
done! https://pypi.python.org/pypi/collective.z3cform.datagridfield/1.3.0

**Comment by tkimnguyen** [comment]
thx @hvelarde
