### ISSUE TITLE
IndexError after upgrade from 1.2 to 1.3.0

### ISSUE THREAD

**Issue by sgeulette** [collective/collective.z3cform.datagridfield#73]
Hi,

I have multiple forms displaying registry records with datagrid field, like https://github.com/collective/collective.contact.plonegroup/blob/44e8011190bc2f0f027152e70430f40b5bf4be84/src/collective/contact/plonegroup/browser/settings.py#L129

After upgrade to 1.3.0, I have the following error on form view:
```
Module zope.tales.tales, line 696, in evaluate
   - URL: /srv/cache/eggs/plone.app.z3cform-0.7.7-py2.7.egg/plone/app/z3cform/templates/multi_input.pt
   - Line 3, Column 8
   - Expression: <PythonExpr (view.key_widgets[repeat['widget'].index()])>
   - Names:
      {'args': (),
       'context': <RecordsProxy for collective.contact.plonegroup.browser.settings.IContactPlonegroupConfig>,
       'default': <object object at 0x7f71623bcc10>,
       'loop': {},
       'nothing': None,
       'options': {},
       'repeat': {},
       'request': <HTTPRequest, URL=http://localhost:8089/troisponts/@@contact-plonegroup-settings>,
       'template': <zope.browserpage.viewpagetemplatefile.ViewPageTemplateFile object at 0x7f714af497d0>,
       'view': <DataGridField 'form.widgets.functions'>,
       'views': <zope.browserpage.viewpagetemplatefile.ViewMapper object at 0x7f71418d0950>}
  Module zope.tales.pythonexpr, line 59, in __call__
   - __traceback_info__: (view.key_widgets[repeat['widget'].index()])
  Module <string>, line 1, in <module>
IndexError: list index out of range

```

Same form is working on a new site...

**Comment by gbastien** [comment]
Hi @jensens @tomgross 

it seems that recent change in JS makes this package no more useable with Plone 4.3.

I suggest describing it clearly on the package homepage and specify that branch 1.2.x is for Plone 4.3 and 1.3+ for Plone 5.

I will propose a PR if that sounds ok to you.

Gauthier

**Comment by idgserpro** [comment]
> it seems that recent change in JS makes this package no more useable with Plone 4.3.

@gbastien What change? Is this relating to @sgeulette's problem? Any chance of working with Plone 4?

**Comment by sgeulette** [comment]
It's not related to this issue that's resolved.

But recent changes like https://github.com/collective/collective.z3cform.datagridfield/blob/master/src/collective/z3cform/datagridfield/static/datagridfield.js#L179

**Comment by idgserpro** [comment]
> But recent changes like https://github.com/collective/collective.z3cform.datagridfield/blob/master/src/collective/z3cform/datagridfield/static/datagridfield.js#L179

@jensens Any chance of working with Plone 4?

**Comment by jensens** [comment]
@idgserpro well, if there is a way... or is it easier to backport other changes?

**Comment by gbastien** [comment]
Hi @idgserpro we use version 1.2 with Plone 4.3 and it works correctly, what recent change do you need?

As discribed (now) in README.rst, versions < 1.3 are for Plone 4.3 and >= 1.3 are for Plone5.

Gauthier

**Comment by idgserpro** [comment]
collective.z3cform.datagridfield is used as a dependency in another package, already in production. Don't know the implications of pinning to older versions after 1.3 was set in place.

**Comment by idgserpro** [comment]
> what recent change do you need? 

@gbastien no specific change I think it's unfortunate that we broke the compatibility because of a JS.

**Comment by gbastien** [comment]
@idgserpro to me 1.3 does not work in Plone4.3...  it is not possible to use it as it has JS errors.

But it registers a BrowserLayer that 1.2 does not have...  So if you downgrade to 1.2, remove the BrowserLayer before.

Gauthier

**Comment by idgserpro** [comment]
@hvelarde FYI.

**Comment by idgserpro** [comment]
> Same form is working on a new site...

@sgeulette I see that ```collective.contact.plonegroup``` only works with [Plone 4](https://github.com/collective/collective.contact.plonegroup/blob/8ba9c95c7d698db9ed87260c4df55d15eae77ee9/setup.py#L30).

The form realy worked with ```collective.z3cform.datagridfield``` 1.3?

I'can confirm a JS error in Plone 4:

```ReferenceError: require is not defined```

**Comment by sgeulette** [comment]
collective.contact.* will also be compatible with plone 5 in the next year I think.
Currently I downgraded to datagridfield 1.2 because it's not working with 1.3.
@idgserpro Are you using plonegroup "standalone" or with one of our "meta" product ?

**Comment by idgserpro** [comment]
@sgeulette I 'm not using ```collective.contact.plonegroup```. I was just wanting to confirm that ```collective.z3cform.datagridfield``` 1.3 doesn't work with Plone 4. I mentioned ```collective.contact.plonegroup``` because it was your example in the description of the issue and it only works with Plone 4.

By the way, this issue may be closed, once you did https://github.com/collective/collective.z3cform.datagridfield/pull/74.
