### ISSUE TITLE
release 1.3.1

### ISSUE THREAD

**Issue by tdesvenain** [collective/collective.z3cform.datagridfield#81]
Hi could we have a 1.3.1 release please ?

**Comment by mauritsvanrees** [comment]
1.3.1 has since been released.
And things apparently move fast: we are already at 1.5.1. :-)

**Comment by tdesvenain** [comment]
thanks !

**Comment by mauritsvanrees** [comment]
Note that 1.3.1 is also the last release that works on Plone 4.3. See comment on [community.plone.org](https://community.plone.org/t/plone-4-3-18-collective-cookiecuttr-install-a-strange-unknown-1-5-1-egg/8426/5?u=mauritsvanrees).

**Comment by idgserpro** [comment]
@mauritsvanrees the 1.3.x not works on Plone 4.3. See:

https://github.com/collective/collective.z3cform.datagridfield/issues/73#issuecomment-426997288
