### ISSUE TITLE
Release 1.3.2

### ISSUE THREAD

**Issue by gbastien** [collective/collective.z3cform.datagridfield#86]
Hi @mauritsvanrees @tdesvenain @idgserpro @jone 

we tested and merged the branch (#85) fixing issue with version 1.3.1 (see #81), now branch 1.3.x works on Plone 4.3.x, can we have a new release?

Thank you!

Gauthier

**Comment by mauritsvanrees** [comment]
Sure. I have released 1.3.2.

**Comment by gbastien** [comment]
Wouhou ;-)
