### ISSUE TITLE
Release 1.3.3 please ;-)

### ISSUE THREAD

**Issue by gbastien** [collective/collective.z3cform.datagridfield#87]
Hi @mauritsvanrees 

can we have a release 1.3.3?  I included the missing upgrade step that adds the browserlayer (cherry-picked from master).

Thank you!

Gauthier

**Comment by gbastien** [comment]
Hi @mauritsvanrees @jensens 

I see I am maintainer on pypi for this package, is it ok if I release it?

Is there some process with that kind of release like announce on community or so?

Thank you!

Gauthier

**Comment by mauritsvanrees** [comment]
Hi Gauthier,
Go ahead and make a release. There is no process. :-)

**Comment by gbastien** [comment]
Released : https://pypi.org/project/collective.z3cform.datagridfield/1.3.3/

Have a nice weekend,

Gauthier
