### ISSUE TITLE
Enable Robot tests

### ISSUE THREAD

**Issue by Gomez** [collective/collective.z3cform.datagridfield#91]
I enabled the Robot test (thx @ksuess for doing the groundwork) but it fails on some Python versions. See this:

https://travis-ci.org/collective/collective.z3cform.datagridfield/builds/594600006

@ksuess You have idea? Here is the PR: https://github.com/collective/collective.z3cform.datagridfield/pull/90

**Comment by ksuess** [comment]
Just restartet single failing jobs. So they are all OK now. Your Pull Request is ready to merge.
