### ISSUE TITLE
Autoappend does not work. Robot test test_autoappend.robot is correct?

### ISSUE THREAD

**Issue by oggers** [collective/collective.z3cform.datagridfield#92]
Watch the video [test_autoappend.robot]( https://youtu.be/7vBWmqecm7Q) I have recorded. There you can see in the final part that there is no new row appended when the test fills the two fields in spite of the test resulting ok.

I have patched static/datagridfield.js and run a newly created robot test. Here you can see the video [test_autoappend2.robot](https://youtu.be/xO3tVMypPgU). In this case you can see the row added (0:35).

[test_autoappend2.robot.zip](https://github.com/collective/collective.z3cform.datagridfield/files/3929320/test_autoappend2.robot.zip)
[datagridfield.js.patch.zip](https://github.com/collective/collective.z3cform.datagridfield/files/3929330/datagridfield.js.patch.zip)

**Comment by ksuess** [comment]
I can reproduce the problem. In some cases dataGridField2Functions.init() is not called. I'll do a bug fix.

**Comment by Gomez** [comment]
Thanks! Merged!

**Comment by ksuess** [comment]
Hi @mauritsvanrees, do you want to make a release?

**Comment by agitator** [comment]
maybe wait for https://github.com/collective/collective.z3cform.datagridfield/pull/95 and include that as well?

**Comment by ksuess** [comment]
Yes, that makes sense.
Hi @mauritsvanrees / some kind person doing releases in datagridfield, please wait with a release for pull request #95.

**Comment by mauritsvanrees** [comment]
I have released `collective.z3cform.datagridfield` 1.5.2 with both fixes.
